SELECT    B.GPDM AS 证券代码,	B.ZQJC AS 证券简称,
    CAST(A.XXFBRQ AS DATE) 信息发布日期 , CAST(A.JZRQ AS DATE) 截止日期 ,
    A.XXLY  信息来源 ,	A.XH 序号,A.XMMC 项目名称 , A.YGSL 员工数量,	
    MAX(CASE WHEN A.HBBZ= '1' THEN A.YGSL END) AS 合并,
    MAX(CASE WHEN A.HBBZ= '2' THEN A.YGSL END) AS 母公司,
    A.FLFS 分类方式,
    MAX(CASE WHEN A.FLFS= '3000' THEN A.YGSL END) AS 专业构成,
    MAX(CASE WHEN A.FLFS= '5000' THEN A.YGSL END) AS 教育程度,
    MAX(CASE WHEN A.XMMC= '职工总数' THEN A.YGSL END) AS 职工总数,
    MAX(CASE WHEN A.XMMC= '离退人数' THEN A.YGSL END) AS 离退人数
FROM [10.101.0.212].JYPRIME.dbo.usrGSJYZGGC A	
    JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM	
WHERE  B.ZQLB IN (1,2,41)  AND  B.SSZT IN (1)
AND B.ZQSC IN (83,90,18)	
AND A.JZRQ = '2025-12-31'	
AND A.XXLY='年度报告'
GROUP BY  B.GPDM ,	B.ZQJC,A.XXFBRQ,A.JZRQ,
A.XXLY, A.HBBZ,A.FLFS,A.XH,A.XMMC, A.YGSL
ORDER BY B.GPDM ,A.FLFS  ,A.XH  ASC;
