--盘后行情
SELECT RQ,INBBM,SPJ,ZGJ,ZDJ,KPJ,ZSP,PHCJL,PHCJJE,PHMRSBSL,PHMCSBSL,PHCJBS FROM [10.101.0.212].JYPRIME.dbo.usrPHHQ WHERE RQ='2024-05-16'
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrPHHQ WHERE RQ='2024-05-16'


--融资融券市场统计
SELECT JYRQ,ZBSZ,ZBBZ,ZXBSZ,ZXBBZ,CYBSZ,CYBBZ,DBZJSZ,DBZJBZ,HJ,XXFBRQ,TJQJ,RZYE,RQYE,RZRQYE,LRYEZAGLTSZBZ,RZMRE,RQMCE,RZRQJYE,LRJYEZAGJYEBZ,ZQGSSL,YYBSL,GRTZZSL,JGTZZSL,CYJYDTZZSL,YRZRQFZDTZZSL,QMZHS,BQXKZHS,DBPSZ,DBPGPSZ,DBPZQJJJQTSZ,PJWCDBBL
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQSCTJ WHERE JYRQ='2024-05-15'
SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrRZRQSCTJ WHERE JYRQ='2024-05-15'


--转融通转融资交易汇总
SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrZRTZRZJYHZ WHERE JYRQ='2024-05-15'


--转融通标的证券
select CAST(A.SXRQ AS DATE) 生效日期,A.SCMC 市场名称,A.ZQDM 证券代码,A.ZQJC 证券名称,A.ZQLBMS 证券类别描述,B.MS 状态 
from [10.101.0.212].JYPRIME.dbo.usrZRTBDZQ A JOIN [10.101.0.212].JYPRIME.dbo.usrXTCLB B ON A.ZT=B.DM
where A.ZT=1 AND B.LB=1790 
order by A.ZQDM
select * from [10.101.0.212].JYPRIME.dbo.usrZRTBDZQ order by XGSJ desc
SELECT INBBM FROM [10.101.0.212].JYPRIME.dbo.usrZQZB WHERE GPDM='688695' AND ZQSC='83'


--融资融券交易明细
SELECT XXLY,JYRQ,ZQSC,ZQDM,ZQJC,INBBM,RZYE,RZMRE,RZCHE,RQYL,RQMCL,RQCHL,RQYE,QZRQYE FROM [10.101.0.212].JYPRIME.dbo.usrRZRQJYMX WHERE JYRQ='2024-05-15' ORDER BY 3,6
SELECT XXLY,MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrRZRQJYMX WHERE JYRQ='2024-05-15' GROUP BY XXLY


--转融通可充抵
SELECT SXRQ,XXLY,SCMC,ZQSC,INBBM,ZQDM,ZQJC,ZSL FROM [10.101.0.212].JYPRIME.dbo.usrZRTBDZQMX WHERE SXRQ='2024-05-16' AND ZQDM<>'501006'
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrZRTBDZQMX WHERE SXRQ='2024-05-16' AND ZQDM<>'501006'



--融资融券担保券统计
SELECT JYRQ,INBBM,XH,ZQDM,ZQJC,SRMDBS,DRDBSBD,DRMDBS,DRMDBQSZ,DRMZSZ,DRMZB FROM [10.101.0.212].JYPRIME.dbo.usrRZRQDBQTJ WHERE JYRQ='2024-09-20' ORDER BY XH
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrRZRQDBQTJ WHERE JYRQ='2024-09-20'
SELECT CONVERT(DATE,JYRQ) JYRQ,XH,ZQDM,A.ZQJC,B.ZQSC
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQDBQTJ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
	ON A.INBBM=B.INBBM AND B.ZQSC IN (81)
ORDER BY 1 DESC,2

SELECT DISTINCT(A.INBBM)
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQDBQTJ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
	ON A.INBBM=B.INBBM AND B.ZQSC IN (81)




--转融券交易汇总
SELECT JYRQ,INBBM,XH,ZQDM,ZQJC,QCYL,RCSL,QMYL,QMYE,JQYTLB FROM [10.101.0.212].JYPRIME.dbo.usrZRTZRQJYHZ WHERE JYRQ='2024-05-15' ORDER BY JQYTLB,XH
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrZRTZRQJYHZ WHERE JYRQ='2024-05-15'


--融资融券交易汇总
SELECT XXLY,JYRQ,ZQSC,TJQJ,RZYE,RZMRE,RZCHE,RQYLJE,JYZJE,RQMCL,RQYL FROM [10.101.0.212].JYPRIME.dbo.usrRZRQJYHZ WHERE JYRQ='2024-05-15' ORDER BY ZQSC 
SELECT XXLY,MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrRZRQJYHZ WHERE JYRQ='2024-05-15' GROUP BY XXLY


--行情表
SELECT RQ,A.INBBM,ZSP,JKP,ZGJ,ZDJ,SPJ,CJL,CJJE,CJBS,SZ 
FROM usrHQ A 
JOIN usrZQZB B ON A.INBBM=B.INBBM 
WHERE A.RQ = '2024-03-07' AND B.ZQLB IN (1,2,41) 
AND ((A.CJL!=0 AND A.CJJE!=0 AND B.ZQSC IN (18))
OR  B.ZQSC IN (83))
ORDER BY INBBM

SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrHQ WHERE RQ='2024-03-01'


--上交所行情接口信息表
SELECT INBBM,ZQDM,XXFBRQ,JLGXSJ,YSWJM,ISINDM,ZQJC,CZWZQMC,YWZQMC,JCZQDM,SCZL,SJSZQLB,SSBK,ZQLB,ZQZLB,SJSZQLBMS,HBDW,MZ,KLTZQWSSSL,ZHJYRQ,SSRQ,SETBH,BSLDW,SSLDW,XJSBSLXX,
XJSBSLSX,SJSBSLXX,SJSBSLSX,QSP,SBJGZXBDDW,ZDFXZLX,ZFSXJG,DFXXJG,CQBL,CXJE,SFWRZBD,SFWRQBD,CPZTBZ,BZ FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB
WHERE XXFBRQ='2024-08-05' ORDER BY INBBM
SELECT INBBM,ZQDM,XXFBRQ,JLGXSJ,ZQJC,CPZTBZ,BZ,B.SJSCPZTWS,B.SJSCPZT,B.SJSCPZTMS
FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB A FULL JOIN [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXCPZT B ON A.ID=B.RID WHERE XXFBRQ='2024-08-05' ORDER BY A.INBBM,B.SJSCPZTWS
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB A WHERE XXFBRQ='2024-05-16'


--北交所行情接口信息表
SELECT INBBM,XXFBRQ,ZQDM,ZQJC,YWJC,JCZQ,ISINBM,JYDW,HYZL,HBZL,MGMZ,ZGB,FXSGB,SNMGSY,BNMGSY,JSFL,YHSL,GHFL,GPRQ,QXR,DQR,MBXL,BLDW,SLDW,ZXSBSL,SBZXBDDW,SBCS,HXCS,XJXZ,ZTJG,DTJG,DZJYJGSX,DZJYJGXX,CFGBZ,ZHBL,JYZT,ZQJB,JYLX,ZSSSL,TPBZ,CQCXBZ,WLTPBZ,ZSP
FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB WHERE  XXFBRQ='2024-07-05' ORDER BY 1 DESC
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB WHERE XXFBRQ='2024-05-16'


--转融通转融券交易明细
select A.XH 序号,A.ZQDM 证券代码,A.ZQJC 证券简称,A.PZ 品种,A.RCFL 融出费率,A.RCSL 融出数量,JQYTLB
from [10.101.0.212].JYPRIME.dbo.usrZRTZRQJYMX A
WHERE A.JYRQ='2024-05-15'
order by JQYTLB,A.ZQDM,RCFL,RCSL
SELECT MIN(FBSJ),MAX(FBSJ) FROM [10.101.0.212].JYPRIME.dbo.usrZRTZRQJYMX WHERE JYRQ='2024-05-15'


--转融通参与人名单
SELECT B.MS 证券分类,A.ZQGS,A.QYBH 企业编号,cast(A.SXRQ as date) 生效时间  
FROM  [10.101.0.212].JYPRIME.dbo.usrZRTCYRMD A ,[10.101.0.212].JYPRIME.dbo.usrXTCLB B
where A.ZT=1 AND B.LB=1848
 and A.ZGFL=B.DM
ORDER BY A.ZGFL

SELECT * FROM  [10.101.0.212].JYPRIME.dbo.usrZRTCYRMD 


--股份变动
SELECT DM,JC,INBBM,IGSDM,XXFBRQ,TBRQ,BDRQ,XH,LDXM,ZWMS,GFBDRXM,GX,GPZL,HBZL,BDQCGS,BDGS,BDJJ,BDBL,BDHCGS,BDYY,ZJCGBL,JJCGBL,HJCGBL 
FROM [10.101.0.212].JYPRIME.dbo.usrGSJYLDRGFBD WHERE XXFBRQ='2024-09-20' AND (DM LIKE '8%' OR DM LIKE '4%') ORDER BY DM

SELECT DM,JC,INBBM,IGSDM,XXFBRQ,TBRQ,BDRQ,XH,LDXM,ZWMS,GFBDRXM,GX,GPZL,HBZL,BDQCGS,BDGS,BDJJ,BDBL,BDHCGS,BDYY,ZJCGBL,JJCGBL,HJCGBL 
FROM [10.101.0.212].JYPRIME.dbo.usrGSJYLDRGFBD WHERE DM LIKE '8%' OR DM LIKE '4%'
ORDER BY 3,7,8


--深交所行情接口信息表
SELECT A.INBBM,A.ZQDM,A.XXFBRQ,A.ZQSC,A.ZQJC,A.KWZQJC,A.YWJC,A.ISINDM,A.JCZQDM,A.JCZQZQSC,A.SSRQ,A.SSBK,A.ZQLB,A.SJSZQLB,A.SJSZQLBMS,A.HBZL,A.SLDW,A.SFZCDRHZJY,A.ZRSPJ,A.ZFXL,A.LTGS,A.MZ,A.SFKZWRZRQKCDBZJZQ,A.KCDBZJZSL,A.SFWRZBD,A.SFWRQBD,A.BJJCFS,A.SFKDYRK,A.DHGBZQZSL,A.DYHGBZQ,A.
SFXYSDXGL,A.TZZSDXGLFL,A.HYZL,A.SNMGLR,A.BNMGLR,A.SFCYYYSGQ,A.GPSX,A.SFSWYL,A.SFCZTPQCY,A.SFZCZ,A.SFJYXYKZJG,A.TJYRJJJZ,A.PMNLL,A.TXFXJ,A.MZZQYJLX,A.FXQXR,A.DQR,A.SFCYZGHSQ,A.SFCYZGQ,A.SFCYHSQ,A.SFCYHSCXQ,A.QZXQJ,A.QZXQBL,A.QZXQQSR,A.QZXQJZR,A.QZRGHRG,A.QZJGFS,A.QZJSJG,A.QZXQFS,A.
QZZHJYR,A.GHQX,A.QQRGHRG,A.QQGPLX,A.QQJGRQ,A.QQJGYF,A.QQJGFS,A.XQQSRQ,A.XQJSRQ,A.QQXQJ,A.QQXQFS,A.QQZHJYR,A.TZCS,A.HYDW,A.ZRJSJ,A.HYCCL,A.PMGXL,A.SFCYZGHSSHQ,A.ZCZCZQDQR,A.YSWJM,A.XJBSLSX,A.XJSSLSX,A.XJBSLDW,A.XJSSLDW,A.SJBSLSX,A.SJSSLSX,A.SJBSLDW,A.SJSSLDW,A.JGDW,A.SFYZDXZ,A.
ZDXZLX,A.SZFD,A.XDFD,A.SZXJ,A.XDXJ,A.SFYYXSBJGFWXZ,A.YXFWXZLX,A.YXFWJZJLX,A.YXFWZDFD,A.YXFWZDJG,B.ZQZT,B.ZQZTMS
FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB A FULL JOIN [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXZQZT B ON A.ID=B.RID WHERE A.XXFBRQ='2024-08-05' ORDER BY 1

SELECT A.INBBM,A.ZQDM,A.XXFBRQ,A.ZQSC,A.ZQJC,A.KWZQJC,A.YWJC,A.ISINDM,A.JCZQDM,A.JCZQZQSC,A.SSRQ,A.SSBK,A.ZQLB,A.SJSZQLB,A.SJSZQLBMS,A.HBZL,A.SLDW,A.SFZCDRHZJY,A.ZRSPJ,A.ZFXL,A.LTGS,A.MZ,A.SFKZWRZRQKCDBZJZQ,A.KCDBZJZSL,A.SFWRZBD,A.SFWRQBD,A.BJJCFS,A.SFKDYRK,A.DHGBZQZSL,A.DYHGBZQ,A.
SFXYSDXGL,A.TZZSDXGLFL,A.HYZL,A.SNMGLR,A.BNMGLR,A.SFCYYYSGQ,A.GPSX,A.SFSWYL,A.SFCZTPQCY,A.SFZCZ,A.SFJYXYKZJG,A.TJYRJJJZ,A.PMNLL,A.TXFXJ,A.MZZQYJLX,A.FXQXR,A.DQR,A.SFCYZGHSQ,A.SFCYZGQ,A.SFCYHSQ,A.SFCYHSCXQ,A.QZXQJ,A.QZXQBL,A.QZXQQSR,A.QZXQJZR,A.QZRGHRG,A.QZJGFS,A.QZJSJG,A.QZXQFS,A.
QZZHJYR,A.GHQX,A.QQRGHRG,A.QQGPLX,A.QQJGRQ,A.QQJGYF,A.QQJGFS,A.XQQSRQ,A.XQJSRQ,A.QQXQJ,A.QQXQFS,A.QQZHJYR,A.TZCS,A.HYDW,A.ZRJSJ,A.HYCCL,A.PMGXL,A.SFCYZGHSSHQ,A.ZCZCZQDQR,A.YSWJM,A.XJBSLSX,A.XJSSLSX,A.XJBSLDW,A.XJSSLDW,A.SJBSLSX,A.SJSSLSX,A.SJBSLDW,A.SJSSLDW,A.JGDW,A.SFYZDXZ,A.
ZDXZLX,A.SZFD,A.XDFD,A.SZXJ,A.XDXJ,A.SFYYXSBJGFWXZ,A.YXFWXZLX,A.YXFWJZJLX,A.YXFWZDFD,A.YXFWZDJG
FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB A WHERE A.XXFBRQ='2024-08-05' ORDER BY 1

SELECT XXFBRQ FROM(
SELECT B.* FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXZQZT A JOIN [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB B ON A.RID=B.ID WHERE A.RID IS NOT NULL) A
ORDER BY A.XXFBRQ


--咨询互动平台
SELECT INBBM,ZXHDLX,XH,ZXRQ,ZXSJ,WTQK,WTHF,HFRQ,HFSJ,SJGPDM,SJGPJC,CWSFSS,SJJYM,XXLY,TWR FROM [10.101.0.212].JYPRIME.dbo.usrSSGSZXHDPT WHERE HFRQ='2024-05-16' ORDER BY 1,5,3,6




--预约披露日
SELECT B.GPDM,CONVERT(DATE,JZRQ) JZRQ,CONVERT(DATE,XXFBRQ) XXFBRQ,CONVERT(DATE,SCYYRQ) SCYYRQ,CONVERT(DATE,DYCBGRQ) DYCBGRQ,
CONVERT(DATE,DECBGRQ) DECBGRQ,CONVERT(DATE,DSCBGRQ) DSCBGRQ,CONVERT(DATE,SJPLRQ) SJPLRQ,A.XXLY
FROM [10.101.0.212].JYPRIME.dbo.usrYYPLRLSB A 
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
ON A.INBBM=B.INBBM AND B.ZQSC IN (90,83,18) AND B.ZQLB in (1,2,41)
WHERE JZRQ='2024-09-30' AND A.XXLY='上交所'
ORDER BY XXLY,A.INBBM

SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrYYPLRLSB A JOIN [10.101.0.212].JYPRIME.dbo.usrYYPLRLSB B ON A.INBBM=B.INBBM AND A.JZRQ=B.JZRQ WHERE A.ID!=B.ID AND A.JZRQ>='2010-12-31'
SELECT * FROM usrYYPLRLSB A JOIN usrYYPLRLSB B ON A.INBBM=B.INBBM AND A.JZRQ=B.JZRQ WHERE A.ID!=B.ID AND A.JZRQ>='2010-12-31'






--融资融券标的证券
SELECT SXRQ,XXLY,ZQSC,INBBM,BDLB,JGDM,BZJBL,XYJB,KHXYJB,ZQDM,ZQJC
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ
WHERE XXFBRQ='2024-05-09'
	AND XXLY='国金证券'
ORDER BY BDLB,INBBM







 

SELECT INBBM FROM usrZQZB WHERE ZQSC=83 AND GPDM='501000'








select XXFBRQ,JZRQ,TJWD,XXLY,GPDM,INBBM,ZQJC,CSJYSL,GHJYSL,DGHYL,DGHWXSTJZQYL,DGHYXSTJZQYL,WXSGFZYSL,YXSGFZYSL,AGZGB,ZYBS,ZYBL
FROM [10.101.0.212].JYPRIME.dbo.usrGPZYHGMX 
WHERE JZRQ='2024-3-26' 
AND XXLY=2
ORDER BY 1


select XXFBRQ,JZRQ,TJWD,XXLY,GPDM,INBBM,ZQJC,CSJYSL,GHJYSL,DGHYL,DGHWXSTJZQYL,DGHYXSTJZQYL,WXSGFZYSL,YXSGFZYSL,AGZGB,ZYBS,ZYBL
FROM [10.101.0.212].JYPRIME.dbo.usrGPZYHGMX 
WHERE JZRQ='2024-3-26' 
AND XXLY=1
ORDER BY 1


select *
FROM [10.101.0.212].JYPRIME.dbo.usrGQJYSCGK 
WHERE JZRQ='2024-3-26' 
ORDER BY 7



--融资融券可充抵



SELECT XXLY,CONVERT(DATE,SXRQ) SXRQ,COUNT(ID) 数量,MAX(XGSJ) LASTTIME FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQMX WHERE XXFBRQ='2024-10-11' GROUP BY XXLY,SXRQ ORDER BY XXLY


SELECT XXFBRQ,XXLY,SXRQ,JGDM,ZQSC,INBBM,PZMX,ZSL,ZQDM,ZQJC,ZQLB
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQMX
WHERE XXFBRQ='2024-10-11'
	AND XXLY='上交所'
ORDER BY ZQDM