
--熔断查询
SELECT ProjectName 熔断表单中文名称,InsertCnt 日增量,UpdateCnt 数据刷新,DeleteCnt 数据删除,TotalCnt 总累计熔断值,Flag
FROM [10.101.0.212].JYDB.dbo.TableCircuitBreaker WHERE TableName='DZ_PerformanceForecast'





--融资融券指标数据提取
SELECT CASE
           WHEN B.ZWJC='中信证券山东' THEN '中信证券(山东)'
       ELSE B.ZWJC END AS ZWJC,
       CASE
           WHEN A.ZBDM=100 THEN '融资利率'
           WHEN A.ZBDM=101 THEN '融券费率'
       END AS ZBDM,
       A.ZBSJ*100 ZBSJ,
       CONVERT(DATE,A.SXRQ) SXRQ
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQZB A
    JOIN [10.101.0.212].JYPRIME.dbo.usrQYSJQYGK B ON A.ZQGS=B.QYBH
WHERE A.JZRQ IS NULL AND A.ZBDM IN ('100','101')
ORDER BY A.ZQGS,A.ZBDM


--业绩预告高峰期预测
SELECT JZRQ,XXFBRQ,COUNT(*) FROM (
SELECT DISTINCT CONVERT(DATE,JZRQ) JZRQ,CONVERT(DATE,XXFBRQ) XXFBRQ,INBBM
FROM [10.106.22.60].JYFIN.dbo.usrCWJCZBZYCYJYGCJB
WHERE XXLYBM='FCC000001E16'
GROUP BY JZRQ,XXFBRQ,INBBM
) M
GROUP BY JZRQ,XXFBRQ HAVING COUNT(*)>20
ORDER BY 1 DESC,2 DESC




SELECT
distinct
    D.GPDM,
    A.CompanyCode,
	A.EndDate,
	A.InfoPublDate AS 信息发布日期,
    C.XXFBSJ AS [FWB-信息发布时间],
    C.FBSJ AS [FWB-FBSJ],
    CASE WHEN C.XXFBSJ IS NOT NULL AND C.FBSJ IS NOT NULL AND C.XXFBSJ<=C.FBSJ THEN C.XXFBSJ
	     WHEN C.XXFBSJ IS NOT NULL AND C.FBSJ IS NOT NULL AND C.XXFBSJ>C.FBSJ THEN C.FBSJ
		 WHEN (C.XXFBSJ IS NULL OR C.FBSJ IS NULL) THEN isnull(C.XXFBSJ,C.FBSJ)
	     else NULL
	end as [最早公告时间],
    E.InsertTime AS 产品层首次入库时间,
	ABS(DATEDIFF(SECOND, E.InsertTime,
	(CASE WHEN C.XXFBSJ IS NOT NULL AND C.FBSJ IS NOT NULL AND C.XXFBSJ<=C.FBSJ THEN C.XXFBSJ
	     WHEN C.XXFBSJ IS NOT NULL AND C.FBSJ IS NOT NULL AND C.XXFBSJ>C.FBSJ THEN C.FBSJ
	     else isnull(C.XXFBSJ,C.FBSJ)
	end )
	) / 60.0) AS 数据源到JYDB时间差

		INTO ##时效

FROM [10.101.0.212].JYDB.dbo.DZ_PerformanceForecast A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB D ON A.CompanyCode=D.IGSDM AND D.GKBZ=3 AND D.ZQLB IN (1,41) AND D.ZQSC IN (83,90,18) AND SSZT=1
OUTER APPLY (SELECT TOP 1 * FROM [10.101.0.212].JYPRIME.dbo.usrGSGGYWFWB  WHERE A.CompanyCode=IGSDM and A.InfoPublDate=XXFBRQ AND (XXBT like '%业绩预%' ) ORDER BY FBSJ ASC) C
OUTER APPLY (SELECT TOP 1 * FROM [10.101.0.212].JYDB.dbo.DZ_PerformanceForecast WHERE CompanyCode=A.CompanyCode AND EndDate=A.EndDate AND InfoPublDate=A.InfoPublDate ORDER BY InsertTime ASC) E
JOIN [10.106.22.60].JYFIN.dbo.usrCWJCZBZYCYJYGCJB F ON A.CompanyCode=F.IGSDM AND A.EndDate=F.JZRQ AND A.InfoPublDate=F.XXFBRQ AND F.GKBZ=3
WHERE
A.ForcastType<>6--经营计划
AND A.ForecastObject NOT IN (70,73)--扣除后营业收入 为新增的科目，时间不准确
AND F.XXLYBM NOT IN ('FCC000001E2S','FCC00000006E','FCC00000006D','FCC000001E2S','FCC00000006H','FCC00000006F','FCC000001E2T')
AND A.EndDate='20241231'
--AND C.XXFBSJ IS NULL AND  C.FBSJ IS NULL--针对性排查为空的情况
--AND H.XXFBSJ IS NULL AND  H.FBSJ IS NULL--针对性排查为空的情况


SELECT [0-30]=SUM(CASE WHEN 数据源到JYDB时间差>=0 AND 数据源到JYDB时间差<30 THEN 1 ELSE 0 END ),
[30-60]=SUM(CASE WHEN 数据源到JYDB时间差>=30 AND 数据源到JYDB时间差<60 THEN 1 ELSE 0 END ),
[60-120]=SUM(CASE WHEN 数据源到JYDB时间差>=60 AND 数据源到JYDB时间差<120 THEN 1 ELSE 0 END ),
[120-180]=SUM(CASE WHEN 数据源到JYDB时间差>=120 AND 数据源到JYDB时间差<180 THEN 1 ELSE 0 END ),
[180-240]=SUM(CASE WHEN 数据源到JYDB时间差>=180 AND 数据源到JYDB时间差<=240 THEN 1 ELSE 0 END ),
[240]=SUM(CASE WHEN 数据源到JYDB时间差>240  THEN 1 ELSE 0 END ),
总计=COUNT(*),
[0-30]=AVG(CASE WHEN 数据源到JYDB时间差>=0 AND 数据源到JYDB时间差<30 THEN  数据源到JYDB时间差 END ),
[30-60]=AVG(CASE WHEN 数据源到JYDB时间差>=30 AND 数据源到JYDB时间差<60 THEN 数据源到JYDB时间差 END ),
[60-120]=AVG(CASE WHEN 数据源到JYDB时间差>=60 AND 数据源到JYDB时间差<120 THEN 数据源到JYDB时间差 END ),
[120-180]=AVG(CASE WHEN 数据源到JYDB时间差>=120 AND 数据源到JYDB时间差<180 THEN 数据源到JYDB时间差 END ),
[180-240]=AVG(CASE WHEN 数据源到JYDB时间差>=180 AND 数据源到JYDB时间差<240 THEN 数据源到JYDB时间差 END ),
[240]=AVG(CASE WHEN 数据源到JYDB时间差>=240  THEN 数据源到JYDB时间差 END )
FROM ##时效
where 最早公告时间  is not null




--股东大会清洗-主持人职位漏处理
SELECT DISTINCT B.GPDM,CONVERT(DATE,A.SCXXFBRQ) 通知日,A.ZCR
FROM [10.101.0.212].JYPRIME.dbo.usrGDDHCX A INNER JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
FULL JOIN [10.101.0.212].JYPRIME.dbo.usrGDDHCX_SL C ON C.ID = A.ID
WHERE C.ID IS NULL AND A.GDCXLB IS NOT NULL AND A.ZCR IS NOT NULL --AND A.SCXXFBRQ > '2024-01-01'
ORDER BY 2 DESC



------------------------------------------------------------------------------------------------------------



SELECT DISTINCT INBBM FROM [10.101.0.212].JYPRIME.dbo.usrGDDHCX WHERE XGSJ>='2025-09-02' AND GDDHGGR IS NOT NULL







--质押统计数据 股东类型--疑似专项，待提
SELECT A.*
FROM [10.106.22.60].JYCFI.dbo.usrGSGDGQZYTJSJ A JOIN [10.101.0.212].JYPRIME.dbo.usrGSGQCT B ON A.INBBM=B.INBBM AND A.GDMC=B.GLFMC
WHERE B.JZRQ=(SELECT MAX(JZRQ) FROM [10.101.0.212].JYPRIME.dbo.usrGSGQCT WHERE INBBM=B.INBBM AND GLFMC=B.GLFMC)
  AND ((B.GQGX=1 AND A.GDLX NOT IN ('FBT000000003','FIC0000000II')) OR (B.GQGX=2 AND A.GDLX NOT IN ('FBT000000003','FIC00000008F')))
  AND ABS(CONVERT(INT,A.JZRQ-B.JZRQ))<180
ORDER BY A.XXFBRQ DESC




select * from [10.101.0.212].JYPRIME_DEL.dbo.usrGSCWZXJSCWZB order by SCSJ desc



WITH #AAA AS (
    SELECT RID,LJDJGS,LJDJZCGSBL,LJDJZZGBBL,rn
    FROM (
        SELECT RID,LJDJGS,LJDJZCGSBL,LJDJZZGBBL,
            ROW_NUMBER() over (partition by RID ORDER BY JZRQ DESC) rn
        FROM [10.101.0.212].JYPRIME.dbo.usrGDGQBDFB
        ) M
    WHERE rn=1
)
SELECT A.ID,A.GQZYSJGS,B.LJDJGS,A.ZDJZYFCGBLQ,B.LJDJZCGSBL,A.GQZYZZGBBL,B.LJDJZZGBBL
FROM [10.101.0.212].JYPRIME.dbo.usrGDGQBD A
    JOIN  #AAA B
        ON A.ID=B.RID AND A.GQZYSJGS=B.LJDJGS
WHERE (A.GQZYZZGBBL IS NOT NULL AND B.LJDJZZGBBL IS NULL)
  OR A.GQZYZZGBBL<>B.LJDJZZGBBL
  OR (A.ZDJZYFCGBLQ IS NOT NULL AND B.LJDJZCGSBL IS NULL)
  OR A.ZDJZYFCGBLQ<>B.LJDJZCGSBL
ORDER BY A.XXFBRQ DESC







select A.INBBM AS INBBM, ISNULL(D.ZQJC,B.ZQJC) AS ZQJC,20 AS FCLB,'' AS TSBS,CONVERT(DATE,KSRQ) AS NRSJ,CONVERT(DATE,JSRQ) AS DCSJ,'' AS 纳入原因,'' AS 调出原因,
       MS+CONVERT(VARCHAR(8), A.GGRQ, 112)+'发布公告,'+ CONVERT(VARCHAR(8), A.KSRQ, 112)+'至'+CONVERT(VARCHAR(8), A.JSRQ, 112)+'对' +ISNULL(D.ZQJC,B.ZQJC)+'进行重点监控' AS FCQKSM,CONVERT(DATE,GGRQ) AS XXFBRQ
from [10.101.0.212].JYPRIME.dbo.usrJYSJGDTSJ A
    JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM=B.INBBM
    LEFT JOIN [10.101.0.212].JYPRIME.dbo.usrXTCLB C ON B.ZQSC=C.DM AND C.LB=201
    OUTER APPLY (SELECT TOP 1 * FROM  [10.101.0.212].JYPRIME.dbo.usrGSMCGGZK WHERE A.INBBM=INBBM AND JCGGRQ IS NOT NULL AND JCGGRQ<=A.GGRQ ORDER BY JCGGRQ DESC) D
WHERE JGLXMS LIKE '%重点监控%' AND JGLXMS NOT LIKE '%证券%' and JGLX=1
  AND GGRQ>'2026-01-01'
ORDER BY NRSJ







--股权变动AI测试
SELECT A.ID,B.GPDM,CONVERT(DATE,A.XXFBRQ) XXFBRQ,CONVERT(DATE,A.JZRQ) JZRQ,
       CASE WHEN A.RQBZ=2 THEN '季度' ELSE '累计' END AS RQBZ,
       A.JBMGSY,A.XSMGSY,A.JBMGSYKC,A.XSMGSYKC,
       CAST(A.JLRJZCSYLJQ AS DECIMAL(18,8)) * 100 AS JLRJZCSYLJQ,
       CAST(A.KCHJLRJZCSYLJQ AS DECIMAL(18,8)) * 100 AS KCHJLRJZCSYLJQ,
       A.YYZSR,A.YYZSRTBZZ*100 YYZSRTBZZ,A.YYSR,A.YYSRTBZZ*100 YYSRTBZZ,A.JLRHJ,A.JLRHJTBZZ*100 JLRHJTBZZ,
       A.JLR,A.JLRTBZZ*100 JLRTBZZ,A.FJCXSY,A.KCFJYXSYHDJLR,A.KCFJYXSYHDJLRTBZZ*100 KCFJYXSYHDJLRTBZZ,
       A.JYXJLLJE,A.MGJYXJLLJE,A.ZCZE,A.GDQYHJ,A.GDQY,A.MGJZCPL
FROM [10.101.0.212].JYPRIME.dbo.usrGSCWZYZB A JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
    ON A.INBBM=B.INBBM AND B.ZQSC IN (18,83,90) AND B.ZQLB IN (1,2,41)
WHERE A.XXLYBM IN (110104,120105) AND A.GGLB = 20 AND
      B.GPDM = ? AND A.XXFBRQ = ?



SELECT *
FROM [10.106.22.60].JYCFI.dbo.usrGSGQZY
WHERE (YTSM LIKE '%经营%' AND YT<>'FCC000000HLT')
    OR (YTSM LIKE '%偿还%' AND YT<>'FCC000000HLU')
    OR (YTSM LIKE '%担保%' AND YTSM NOT LIKE '%反担保%' AND YT<>'FCC000000HLR')
    OR (YTSM LIKE '%反担保%' AND YT<>'FCC000000HLS')
    OR (YTSM LIKE '%融资%' AND YT<>'FCC000000HLQ')



select A.GPDM,CONVERT(varchar(100),B.XXFBRQ,23)
from [10.106.22.60].JYFIN.dbo.usrCWJCZBZYCYJYGCJB B join [10.101.0.212].JYPRIME.dbo.usrZQZB A on A.IGSDM=B.IGSDM AND A.ZQSC IN (90,83)
AND A.ZQLB=1
WHERE
 ((B.YJYJLX<>'FCC000001E1F'
AND B.JZRQ>=convert(char(4),year(dateAdd(YY,1,B.XXFBRQ)))+'1231') OR
(B.YJYJLX='FCC000001E1F'
AND XXLYBM<>'FCC00000005E'))
-- AND B.XXFBRQ>'2020-01-01'
order BY 1,2 DESC








--行情比对
select distinct XXLY,counT(XXLY)
from [10.101.1.144].FSCSJ.dbo.usrGPLSB
WHERE XXLY IN ('高频行情-A股','新浪财经行情数据','东方财富行情数据') AND XGSJ<'2025-01-01'
GROUP BY( XXLY)



SELECT DISTINCT GPDM, SCXXFBRQ
FROM [10.101.0.212].JYPRIME.dbo.usrGDDHCX AS CX
         JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB AS ZB
              ON CX.INBBM = ZB.INBBM AND ZB.ZQSC IN (18, 83, 90) AND ZB.ZQLB IN (1, 2, 41) AND SSZT = 1 AND SCXXFBRQ>SSRQ
WHERE LSSWS IS NULL
  AND GDDHGGR IS NOT NULL  AND CX.SFYX=1 AND  SCXXFBRQ<'2012-1-1'





SELECT A.ID,B.GPDM 股票代码,CONVERT(DATE,A.GQBDQSR) 变动起始日期,CONVERT(DATE,A.GQZSBDRQ) 变动截止日期,
    A.GQCRF 出让方,A.CRQCGSL 出让前持股数量,A.CRHCGSL 出让后持股数量,A.CRHYXSGS 出让后有限售股数,A.CRHWXSGS 出让后无限售股数,
    A.GQZRF 受让方,A.SRQCGSL 受让前持股数量,A.SRHCGSL 受让后持股数量,A.SRHYXSGS 受让后有限售股数,A.SRHWXSGS 受让后无限售股数,
    A.GQBDSJGS 涉及股数,A.JYJG 交易价格区间,A.JYJE 交易总金额,A.GQZRFS 交易方式
FROM [10.101.0.212].JYPRIME.dbo.usrGDGQBD A
 JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
  ON A.INBBM = B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE A.LBXZ = 1 AND B.GPDM = '603169' AND A.GQCRF='湖南华菱湘潭钢铁有限公司' AND A.GQZRF IS NULL



select * from [10.101.0.212].JYPRIME.dbo.usrGDGQBD where IGSDM=200666 and  XXFBRQ='2025-12-02 00:00:00.000' and GQCRF='高明'






SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrGDDHCX WHERE TPBJFS IN (1,3,5,16) AND WLTPQSR IS NULL AND WLTPJZR IS NULL








SELECT HASHCODE,*
     -- ,B.GPDM,B.ZQJC,CONVERT(DATE,A.XXFBRQ) XXFBRQ
FROM [10.101.0.212].JYPRIME.dbo.usrGSGGYWFWB A
     JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE A.XXLB=20 AND A.NRLB=5 AND A.XXLY IN (69,70,410007600) AND A.MTCC IN ('上海证券交易所','深圳证券交易所','北京证券交易所')
  AND A.XXFBRQ BETWEEN '2026-01-01' AND '2026-05-1'
  AND A.XXBT NOT LIKE '%英文%' AND A.XXBT NOT LIKE '%网页已%' AND A.XXBT NOT LIKE '%延期%' AND A.XXBT NOT LIKE '%披露%'
  AND A.XXBT NOT LIKE '%修正%' AND A.XXBT NOT LIKE '%修订%' AND A.XXBT NOT LIKE '%更正%' AND A.XXBT NOT LIKE '%更新%'






SELECT A.HASHCODE,B.JC,B.GDDHLB,B.DBTXH,B.XBTXH,B.SFTG,B.HBBJGS,
       B.QBTYGS,B.QBTYZB*100,B.QBFDGS,B.QBFDZB*100,B.QBQQGS,B.QBQQZB*100,
       B.QBAGTYGS,B.QBAGTYZB*100,B.QBAGFDGS,B.QBAGFDZB*100,B.QBAGQQGS,B.QBAGQQZB*100,
       B.QBHGTYGS,B.QBHGTYZB*100,B.QBHGFDGS,B.QBHGFDZB*100,B.QBHGQQGS,B.QBHGQQZB*100,
       B.QBQTGDTYGS,B.QBQTGDTYZB*100,B.QBQTGDFDGS,B.QBQTGDFDZB*100,B.QBQTGDQQGS,B.QBQTGDQQZB*100,
       B.ZXGDTYGS,B.ZXGDTYZB*100,B.ZXGDFDGS,B.ZXGDFDZB*100,B.ZXGDQQGS,B.ZXGDQQZB*100,
       B.YXGGDTYGS,B.YXGGDTYZB*100,B.YXGGDFDGS,B.YXGGDFDZB*100,B.YXGGDQQGS,B.YXGGDQQZB*100
FROM [10.101.0.212].JYPRIME.dbo.usrGSGGYWFWB A
    JOIN [10.101.0.212].JYPRIME.dbo.usrGDDHBJ B
        ON A.INBBM=B.INBBM AND A.XXFBRQ=B.XXFBRQ
WHERE A.HASHCODE IN ('3D3A9B95785952A82D6ECE46920F5729')









SELECT B.GPDM,CONVERT(DATE,A.XXFBRQ) XXFBRQ,A.XXLY,CONVERT(DATE,A.JZRQ) JZRQ
FROM [10.101.0.212].JYPRIME.dbo.usrGSCWZYZB A
    JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
        ON A.INBBM=B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE NOT EXISTS (SELECT 1 FROM [10.101.0.212].JYPRIME.dbo.usrCWBBZCFZB WHERE IGSDM=A.IGSDM AND XXFBRQ=A.XXFBRQ AND JZRQ=A.JZRQ)
AND A.XXLYBM IN ('130101','130102','130103','130104','130105','130106','130107','130108','130109','130110','130111','130112','130113')



SELECT CONVERT(DATE,A.XXFBRQ),A.IGSDM
FROM [10.101.0.212].JYPRIME.dbo.usrGSCWZYZB A
------JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.IGSDM = B.IGSDM AND B.SSZT IN (83,90,18) AND B.ZQLB IN (1,2,3,41)
WHERE A.JZRQ NOT IN (SELECT JZRQ FROM [10.101.0.212].JYPRIME.dbo.usrCWBBZCFZB WHERE XXFBRQ = A.XXFBRQ AND IGSDM=A.IGSDM )
AND A.XXLYBM IN (130102,130112,130113)
AND A.XXFBRQ >'20250101'



--股东大会出席表决
SELECT GPDM,XXFBRQ,JC,DBTXH,DBT,XBTXH,
       总股数,同意股数+反对股数+弃权股数 同意反对弃权股数,回避股数,
       总股数-同意股数-反对股数-弃权股数 '回避计算'
FROM (
SELECT B.GPDM,CONVERT(DATE,A.SCXXFBRQ) XXFBRQ,A.JC,A.DBTXH,A.DBT,A.XBTXH,ISNULL(A.HBBJGS,0) 回避股数,
    CASE WHEN C.DBGF IS NOT NULL THEN C.DBGF
         WHEN C.ZTAGGDDBGF IS NOT NULL THEN C.ZTAGGDDBGF
         WHEN C.ZTQTGDDBGF IS NOT NULL THEN C.ZTQTGDDBGF END AS '总股数',
	CASE WHEN A.QBTYGS+A.QBFDGS+A.QBQQGS IS NOT NULL THEN A.QBTYGS
	     WHEN A.QBAGTYGS+A.QBAGFDGS+A.QBAGQQGS IS NOT NULL THEN A.QBAGTYGS
	     WHEN A.QBQTGDTYGS+A.QBQTGDFDGS+A.QBQTGDQQGS IS NOT NULL THEN A.QBQTGDTYGS
	ELSE A.QBTYGS END AS '同意股数',
    CASE WHEN A.QBTYGS+A.QBFDGS+A.QBQQGS IS NOT NULL THEN A.QBFDGS
	     WHEN A.QBAGTYGS+A.QBAGFDGS+A.QBAGQQGS IS NOT NULL THEN A.QBAGFDGS
	     WHEN A.QBQTGDTYGS+A.QBQTGDFDGS+A.QBQTGDQQGS IS NOT NULL THEN A.QBQTGDFDGS
    ELSE A.QBFDGS END AS '反对股数',
    CASE WHEN A.QBTYGS+A.QBFDGS+A.QBQQGS IS NOT NULL THEN A.QBQQGS
	     WHEN A.QBAGTYGS+A.QBAGFDGS+A.QBAGQQGS IS NOT NULL THEN A.QBAGQQGS
	     WHEN A.QBQTGDTYGS+A.QBQTGDFDGS+A.QBQTGDQQGS IS NOT NULL THEN A.QBQTGDQQGS
    ELSE A.QBQQGS END AS '弃权股数',
	A.ZXGDTYGS,A.ZXGDFDGS,A.ZXGDQQGS
FROM [10.101.0.212].JYPRIME.dbo.usrGDDHBJ A
    JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM=B.INBBM AND B.ZQSC IN (18,83,90) AND B.ZQLB IN (1,2,41)
    JOIN [10.101.0.212].JYPRIME.dbo.usrGDDHCX C ON A.INBBM=C.INBBM AND A.SCXXFBRQ=C.SCXXFBRQ
WHERE C.SFYX=1 AND C.GDCXLB=1
) M
WHERE 总股数<>同意股数+反对股数+弃权股数+回避股数 AND 总股数-同意股数-反对股数-弃权股数!=0
ORDER BY 2 DESC,1,4,6





SELECT * FROM [10.101.0.212].JYPRIME.dbo.usrZYLDRCG
WHERE INBBM IS NULL 







SELECT A.GPDM,CONVERT(DATE,C.XXFBRQ) XXFBRQ,C.XXBT,C.HASHCODE MD5
FROM [10.101.0.212].JYPRIME.dbo.usrZQZB A,[10.101.0.212].JYPRIME.dbo.usrGSGGYWFWB C
WHERE A.INBBM=C.INBBM
AND A.ZQLB IN (1,2,41)
AND A.ZQSC IN (18,83,90)
AND C.XXLY IN (69,70,410007600)
AND C.MTCC IN ('上海证券交易所','深圳证券交易所', '北京证券交易所')
AND (C.XXBT LIKE '%业绩%'
 OR C.XXBT LIKE '%预增%'
 OR C.XXBT LIKE '%预亏%'
 OR C.XXBT LIKE '%扭亏%'
 OR C.XXBT LIKE '%预盈%'
 OR C.XXBT LIKE '%预减%'
 OR C.XXBT LIKE '%预降%'
 OR C.XXBT LIKE '%质量回报双提升%')
AND C.XXBT NOT LIKE '%意见%'
AND C.XXBT NOT LIKE '%复函%'
AND C.XXBT NOT LIKE '%英文%'
AND C.XXBT NOT LIKE '%问询函%'
AND C.XXBT NOT LIKE '%回函%'
AND C.XXBT NOT LIKE '%快报%'
AND C.XXFBRQ>'2026-01-01'
order by 2 DESC,A.GPDM






--是否通过不为空(即已决议)，但首次信息发布日期等于信息发布日期
SELECT A.ID, B.GPDM,CONVERT(DATE,A.SCXXFBRQ) 通知日
FROM [10.101.0.212].JYPRIME.dbo.usrGDDHBJ A 
INNER JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE A.SFYX = 1 AND A.SFTG IS NOT NULL AND A.SCXXFBRQ = A.XXFBRQ AND A.GKBZ = 3
ORDER BY CONVERT(DATE,A.SCXXFBRQ) DESC





--主要指标退市后处理记录
SELECT C.GPDM,C.ZQJC,CONVERT(DATE,A.XXFBRQ) 信息发布日期,CONVERT(DATE,B.BGRQ) 终止上市日期
FROM [10.101.0.212].JYPRIME.dbo.usrGSCWZYZB A
  JOIN [10.101.0.212].JYPRIME.dbo.usrSSZTGGZK B ON A.INBBM=B.INBBM AND B.BGLX=4
  JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB C ON A.INBBM=C.INBBM AND C.ZQSC IN (83,90,18) AND C.ZQLB IN (1,2,41)
WHERE A.XXFBRQ>B.BGRQ






SELECT B.GPDM,CONVERT(DATE,A.XXFBSJ) XXFBRQ,A.LDXM,A.ZWMS,A.QCCGS,A.CGS,A.JJCG,A.NDBC/10000 NDBC,A.BTJT/10000 NDBC,A.BDYYSM,
    CASE WHEN A.SFZGDHGLDWLQBCJT=1 THEN '是' ELSE '否' END SFZGDHGLDWLQBCJT,
    CASE WHEN A.ZRYF=1 THEN '是' ELSE '否' END ZRYF
FROM [10.101.0.212].JYPRIME.dbo.usrZYLDRCG A
  LEFT JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM=B.INBBM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE A.XXLYBM = 110101 AND B.GPDM = '300995' AND A.XXFBSJ = '2026-03-12'
ORDER BY XH

SELECT B.GPDM,CONVERT(DATE,A.XXFBRQ) XXFBRQ,BCXMLB,BCQJQS,BCQJJZ,SJRS
FROM [10.101.0.212].JYPRIME.dbo.usrGSJYLDRBC A 
    LEFT JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.IGSDM=B.IGSDM AND B.ZQSC IN (83,90,18) AND B.ZQLB IN (1,2,41)
WHERE A.XXLY='年度报告' AND B.GPDM = '300995' AND A.XXFBRQ = '2026-03-12'









SELECT A.ID,B.GPDM,CONVERT(DATE,A.XXFBRQ) XXFBRQ,CONVERT(DATE,A.JZRQ) JZRQ,
       A.JBMGSY,A.XSMGSY,A.JBMGSYKC,A.XSMGSYKC,
       CAST(A.JLRJZCSYLJQ AS DECIMAL(18,8)) * 100 AS JLRJZCSYLJQ,
       CAST(A.KCHJLRJZCSYLJQ AS DECIMAL(18,8)) * 100 AS KCHJLRJZCSYLJQ,
       CAST(A.PTGJZCSYLJQ AS DECIMAL(18,8)) * 100 AS PTGJZCSYLJQ,
       CAST(A.KCPTGJZCSYLJQ AS DECIMAL(18,8)) * 100 AS KCPTGJZCSYLJQ,
       A.YYZSR,A.YYZSRTBZZ*100 YYZSRTBZZ,A.YYSR,A.YYSRTBZZ*100 YYSRTBZZ,A.JLRHJ,A.JLRHJTBZZ*100 JLRHJTBZZ,
       A.JLR,A.JLRTBZZ*100 JLRTBZZ,A.FJCXSY,A.KCFJYXSYHDJLR,A.KCFJYXSYHDJLRTBZZ*100 KCFJYXSYHDJLRTBZZ,
       A.JYXJLLJE,A.MGJYXJLLJE,A.ZCZE,A.GDQYHJ,A.GDQY,A.MGJZCPL,A.GJKJZEJLR,A.GJKJZZJZC
FROM [10.101.0.212].JYPRIME.dbo.usrGSCWZYZB A JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B
    ON A.INBBM=B.INBBM AND B.ZQSC IN (18,83,90) AND B.ZQLB IN (1,2,41)
WHERE A.XXLYBM = 110101 AND A.GGLB = 20 AND RQBZ = 3 AND
      B.GPDM = '002138' AND A.XXFBRQ = '2026-02-28'

