--1、行情北交所底层表，15:05~15:10每分钟执行，数量大于160可停止
SELECT B.GPDM,B.ZQSC,A.FBSJ,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (18) AND B.ZQLB IN (1,2,41) 
WHERE A.RQ = CONVERT(VARCHAR(10),GETDATE(),120)
ORDER BY A.FBSJ DESC

--2、行情沪深底层表，15:05~15:10每分钟执行，数量大于4950可停止
SELECT B.GPDM,B.ZQSC,A.FBSJ,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83,90) AND B.ZQLB IN (1,2,41) 
WHERE A.RQ = CONVERT(VARCHAR(10),GETDATE(),120)
ORDER BY A.FBSJ DESC

--3、成交笔数入库时间,15:06执行,注释倒数第二行看XGSJ列可以得到成交笔数的入库开始时间和截止时间，数量大于2200可停止
SELECT B.GPDM,A.FBSJ,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83) AND B.ZQLB IN (1,2,41)
WHERE A.RQ = CONVERT(VARCHAR(10),GETDATE(),120)
--AND (A.CJBS IS NULL OR A.CJBS = 0) AND A.JKP IS NOT NULL
ORDER BY A.CJBS

--4、行情北交所产品表,15:10~15:20每分钟执行，数量大于160可停止
SELECT B.SecuCode,* FROM [10.101.0.212].JYDB.dbo.QT_DailyQuote A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (18) AND B.SecuCategory IN (1,2,41)
WHERE  A.TradingDay = CONVERT(VARCHAR(10),GETDATE(),120)
ORDER BY 13 DESC

--5、行情沪深产品表,15:10~15:20每分钟执行，数量大于4480可停止
SELECT B.SecuCode,* FROM [10.101.0.212].JYDB.dbo.QT_DailyQuote A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (83,90) AND B.SecuCategory IN (1,2,41)
WHERE  A.TradingDay = CONVERT(VARCHAR(10),GETDATE(),120)
ORDER BY 13 DESC

--6、科创板行情产品表,15:10~15:20每分钟执行，数量大于500可停止
SELECT B.SecuCode,* FROM [10.101.0.212].JYDB.dbo.LC_STIBDailyQuote A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (83) 
WHERE  A.TradingDay = CONVERT(VARCHAR(10),GETDATE(),120)
ORDER BY 13 DESC

--沪深北行情字段比对（底层-产品）
SELECT B.GPDM,CONVERT(DATE,B.RQ) RQ,A.PrevClosePrice,B.ZSP,A.OpenPrice,B.JKP,A.HighPrice,B.ZGJ,
A.LowPrice,B.ZDJ,A.ClosePrice,B.SPJ,A.TurnoverVolume,B.CJL,A.TurnoverValue,B.CJJE,A.TurnoverDeals,B.CJBS 
FROM
(SELECT A.* FROM [10.101.0.212].JYDB.dbo.QT_DailyQuote A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (18,83,90) AND B.SecuCategory IN (1,2,41)
WHERE  A.TradingDay = CONVERT(DATE,GETDATE())) A
FULL JOIN
(SELECT B.GPDM,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (18,83,90) AND B.ZQLB IN (1,2,41) 
WHERE A.RQ = CONVERT(DATE,GETDATE())) B 
ON A.InnerCode=B.INBBM
WHERE A.PrevClosePrice!=B.ZSP OR A.OpenPrice!=B.JKP OR A.HighPrice!=B.ZGJ OR A.LowPrice!=B.ZDJ 
OR A.ClosePrice!=B.SPJ OR A.TurnoverVolume!=B.CJL OR A.TurnoverValue!=B.CJJE OR A.TurnoverDeals!=B.CJBS 

--科创板行情字段比对（底层-产品）
SELECT B.GPDM,CONVERT(DATE,B.RQ) RQ,A.PrevClosePrice,B.ZSP,A.OpenPrice,B.JKP,A.HighPrice,B.ZGJ,
A.LowPrice,B.ZDJ,A.ClosePrice,B.SPJ,A.TurnoverVolume,B.CJL,A.TurnoverValue,B.CJJE,A.TurnoverDeals,B.CJBS 
FROM
(SELECT A.* FROM [10.101.0.212].JYDB.dbo.LC_STIBDailyQuote A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (83) 
WHERE  A.TradingDay = CONVERT(DATE,GETDATE())) A
FULL JOIN
(SELECT B.GPDM,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (83) AND B.ZQLB IN (1,2,41) 
WHERE A.RQ = CONVERT(DATE,GETDATE())) B 
ON A.InnerCode=B.INBBM
WHERE A.PrevClosePrice!=B.ZSP OR A.OpenPrice!=B.JKP OR A.HighPrice!=B.ZGJ OR A.LowPrice!=B.ZDJ 
OR A.ClosePrice!=B.SPJ OR A.TurnoverVolume!=B.CJL OR A.TurnoverValue!=B.CJJE OR A.TurnoverDeals!=B.CJBS 

--聚源数据-比对
SELECT CASE WHEN ZQSC = 18 THEN B.GPDM+'.BJ' WHEN ZQSC = 83 THEN B.GPDM+'.SH' WHEN ZQSC = 90 THEN B.GPDM+'.SZ' END 代码,
CONVERT(DATE,A.RQ) 日期,ISNULL(A.ZSP,0) ZSP,ISNULL(A.JKP,0) JKP,ISNULL(A.ZGJ,0) ZGJ,ISNULL(A.ZDJ,0) ZDJ,ISNULL(A.SPJ,0) SPJ,ISNULL(A.CJL,0) CJL,
CASE WHEN ZQSC = 18 THEN FLOOR(CJJE) ELSE ROUND(CJJE,0) END CJJE,isnull(A.CJBS,0) CJBS FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM AND B.ZQSC IN (18,83,90) AND B.ZQLB IN (1,2,41) AND SSZT = 1
WHERE RQ = FORMAT(GETDATE(),'yyyy-MM-dd')
ORDER BY 1


--盘前行情比对
SELECT *
FROM (
SELECT A.ZQDM,A.XXFBRQ, A.QSP,A.ZFSXJG,A.DFXXJG,A.BSLDW,A.SSLDW,A.XJSBSLXX,A.XJSBSLSX,A.SJSBSLXX,A.SJSBSLSX 
FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B 
ON A.INBBM = B.INBBM AND B.ZQSC IN (83) AND B.ZQLB IN (1,2,41) 
WHERE A.XXFBRQ = CONVERT(DATE,GETDATE())
UNION ALL
SELECT A.ZQDM,A.XXFBRQ,A.ZRSPJ,CONVERT(DECIMAL(18,2),A.ZRSPJ*(1+SZFD)) ZFSXJG,CONVERT(DECIMAL(18,2),A.ZRSPJ*(1-SZFD)) DFXXJG,A.XJBSLDW,A.XJSSLDW,1 LmtOrdMin,A.XJBSLSX,1 MktOrdMin,A.SJBSLSX
FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B 
ON A.INBBM = B.INBBM AND B.ZQSC IN (90) AND B.ZQLB IN (1,2,41) 
WHERE A.XXFBRQ = CONVERT(DATE,GETDATE())
UNION ALL
SELECT A.ZQDM,A.XXFBRQ,A.ZSP,A.ZTJG,A.DTJG,A.BLDW,A.SLDW,A.ZXSBSL,A.MBXL,A.ZXSBSL,A.MBXL 
FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B 
ON A.INBBM = B.INBBM AND B.ZQSC IN (18) AND B.ZQLB IN (1,2,41) 
WHERE A.XXFBRQ = CONVERT(DATE,GETDATE())) A
FULL JOIN
(SELECT B.SecuCode,TradingDay,PrevClosePrice,PriceCeiling,PriceFloor,BuyNumUnit,SellNumUnit,LmtOrdMin,LmtOrdMax,MktOrdMin,MktOrdMax,A.ID
FROM [10.101.0.212].JYDB.dbo.DZ_PriceLimit A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B 
ON A.InnerCode = B.InnerCode 
WHERE A.TradingDay=CONVERT(DATE,GETDATE())) B
ON A.ZQDM=B.SecuCode
WHERE A.QSP<>B.PrevClosePrice
OR A.ZFSXJG<>B.PriceCeiling
OR A.DFXXJG<>B.PriceFloor
OR A.BSLDW<>B.BuyNumUnit
OR A.SSLDW<>B.SellNumUnit
OR A.XJSBSLXX<>B.LmtOrdMin
OR A.XJSBSLSX<>B.LmtOrdMax
OR A.SJSBSLXX<>B.MktOrdMin
OR A.SJSBSLSX<>B.MktOrdMax
OR B.ID IS NULL

--上交所盘前行情全字段比对 19:30分开始
SELECT *
FROM (
SELECT A.ZQDM,A.XXFBRQ, A.QSP,A.ZFSXJG,A.DFXXJG,A.BSLDW,A.SSLDW,A.XJSBSLXX,A.XJSBSLSX,A.SJSBSLXX,A.SJSBSLSX 
FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B 
ON A.INBBM = B.INBBM AND B.ZQSC IN (83) AND B.ZQLB IN (1,2,41) 
WHERE A.XXFBRQ=CONVERT(DATE,DATEADD(DAY,1,GETDATE()))
) A 
FULL JOIN (
SELECT B.SecuCode,TradingDay,PrevClosePrice,PriceCeiling,PriceFloor,BuyNumUnit,SellNumUnit,LmtOrdMin,LmtOrdMax,MktOrdMin,MktOrdMax,A.ID
FROM [10.101.0.212].JYDB.dbo.DZ_PriceLimit A
JOIN [10.101.0.212].JYDB.dbo.SecuMain B 
ON A.InnerCode = B.InnerCode AND B.SecuMarket IN (83)
WHERE A.TradingDay=CONVERT(DATE,DATEADD(DAY,1,GETDATE()))
) B ON A.ZQDM=B.SecuCode
WHERE A.QSP<>B.PrevClosePrice
OR A.ZFSXJG<>B. PriceCeiling
OR A.DFXXJG<>B. PriceFloor
OR A.BSLDW<>B. BuyNumUnit
OR A.SSLDW<>B. SellNumUnit
OR A.XJSBSLXX<>B. LmtOrdMin
OR A.XJSBSLSX<>B. LmtOrdMax
OR A.SJSBSLXX<>B. MktOrdMin
OR A.SJSBSLSX<>B. MktOrdMax
OR B.ID IS NULL



--北交所补录行情 专项
SELECT B.GPDM,CONVERT(DATE,A.RQ) 日期,A.* FROM [10.101.0.212].JYPRIME.dbo.usrHQ A
JOIN [10.101.0.212].JYPRIME.dbo.usrZQZB B ON A.INBBM = B.INBBM 
AND B.ZQSC =　18 AND B.ZQLB IN (1,2,41)WHERE A.CJL <>0　AND　CJBS = 0
ORDER BY RQ DESC

--北交所补录盘前行情 交易日漏数据
SELECT A.ZQDM,B.RQ FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB A
RIGHT JOIN [10.101.0.212].JYPRIME.dbo.usrJYR B ON A.XXFBRQ=B.RQ
WHERE B.ZQSC=18 AND B.SFJYR=1 AND A.ID IS NULL AND B.RQ<=CONVERT(DATE,GETDATE()) 
ORDER BY 2 DESC 
A.ZQDM='870656'

--行情数据汇总 
SELECT '上交所盘前行情',COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT '深交所盘前行情',COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT '北交所盘前行情',COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT '盘前行情总和',SUM(数量) FROM 
(SELECT COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrSHJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrSZJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrBJJSHQJKXXB WHERE XXFBRQ=CONVERT(DATE,GETDATE())) AS A
UNION ALL
SELECT '盘后行情',COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrPHHQ WHERE RQ=CONVERT(DATE,GETDATE())
UNION ALL
SELECT '行情',COUNT(ID) 数量 FROM [10.101.0.212].JYPRIME.dbo.usrHQ WHERE RQ=CONVERT(DATE,GETDATE())



