--查错-融资融券标的证券-数据重复
SELECT A.ID IDA,A.ZQDM 证券代码A,A.XXLY 信息来源A,A.XXFBRQ 信息发布日期A,A.BDLB 变动类别A,A.KHXYJB 客户信用等级A,
       B.ID IDB,B.ZQDM 证券代码B,B.XXLY 信息来源B,B.XXFBRQ 信息发布日期B,B.BDLB 变动类别B,B.KHXYJB 客户信用等级B
FROM
(SELECT ID,XXFBRQ,XXLY,BDLB,SXRQ,ZQDM,KHXYJB
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ WHERE XXFBRQ=FORMAT(GETDATE(),'yyyy-MM-dd'))A
JOIN
(SELECT ID,XXFBRQ,XXLY,BDLB,SXRQ,ZQDM,KHXYJB
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ WHERE XXFBRQ=FORMAT(GETDATE(),'yyyy-MM-dd'))B
ON A.ZQDM=B.ZQDM AND A.XXLY=B.XXLY AND A.BDLB=B.BDLB AND A.KHXYJB=B.KHXYJB
WHERE A.ID<>B.ID
