--查错-融资融券标的状态-状态比例需要变更-东方证券
SELECT A.XXLY,A.ZQDM,A.XXFBRQ XXFBRQ1,A.BDLB BDLB1,A.BZJBL BZJBL1,B.XXLY,B.ZQDM,B.XXFBRQ XXFBRQ2,B.BDLB BDLB2,B.BZJBL BZJBL2
FROM
(SELECT XXLY,ZQDM,INBBM,XXFBRQ,BDLB,BZJBL,KHXYJB
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ
WHERE JGDM=41086 AND XXFBRQ=(SELECT TOP 1 RQ FROM   [10.101.0.212].JYPRIME.dbo.usrJYR WHERE ZQSC=83 AND SFJYR=1 AND RQ<=CONVERT(VARCHAR(10),GETDATE(),120) ORDER BY RQ DESC))A
FULL JOIN
(SELECT XXLY,ZQDM,INBBM,XXFBRQ,BDLB,BZJBL,KHXYJB
FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ
WHERE JGDM=41086 AND XXFBRQ=(SELECT TOP 1 RQ FROM   [10.101.0.212].JYPRIME.dbo.usrJYR WHERE ZQSC=83 AND SFJYR=1 AND RQ<CONVERT(VARCHAR(10),GETDATE(),120) ORDER BY RQ DESC))B
ON A.XXLY=B.XXLY AND A.INBBM=B.INBBM AND A.BDLB=B.BDLB AND A.KHXYJB=B.KHXYJB
WHERE A.INBBM IS NULL OR B.INBBM IS NULL OR A.BZJBL<>B.BZJBL
ORDER BY A.XXLY,A.ZQDM DESC