-- 深交所
SELECT  A.ZQDM,BDLB,SXRQ 生效日期,BDLX,RXRQ 变更日期,XXLY FROM
(SELECT ZQDM,ZQJC,INBBM,BDLB,SXRQ,XXLY FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY SXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ with(nolock) WHERE ZQSC=90 AND JGDM='25404'  ) t WHERE rn = 1  ) A
FULL JOIN
(SELECT INBBM,BDLX,RXRQ FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY RXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQZT with(nolock) WHERE ZQSC=90 AND JGDM='25404'  ) t WHERE rn = 1  ) B
ON A.INBBM=B.INBBM
WHERE   B.INBBM IS NULL
union all
-- 上交所
SELECT  A.ZQDM,BDLB,SXRQ 生效日期,BDLX,RXRQ 变更日期,XXLY FROM
(SELECT ZQDM,ZQJC,INBBM,BDLB,SXRQ,XXLY FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY SXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ with(nolock) WHERE ZQSC=83 AND JGDM='25403'  ) t WHERE rn = 1  ) A
FULL JOIN
(SELECT INBBM,BDLX,RXRQ FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY RXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQZT with(nolock) WHERE ZQSC=83 AND JGDM='25403'  ) t WHERE rn = 1  ) B
ON A.INBBM=B.INBBM
WHERE  B.INBBM IS NULL
union all
-- 北交所
SELECT  A.ZQDM,BDLB,SXRQ 生效日期,BDLX,RXRQ 变更日期,XXLY FROM
(SELECT ZQDM,ZQJC,INBBM,BDLB,SXRQ,XXLY FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY SXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ with(nolock) WHERE ZQSC=18 AND JGDM='95051632'  ) t WHERE rn = 1  ) A
FULL JOIN
(SELECT INBBM,BDLX,RXRQ FROM (SELECT  *, ROW_NUMBER() OVER (PARTITION BY INBBM ORDER BY RXRQ ASC) rn FROM [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQZT with(nolock) WHERE ZQSC=18 AND JGDM='95051632'  ) t WHERE rn = 1  ) B
ON A.INBBM=B.INBBM
WHERE  B.INBBM IS NULL


