--查错-融资融券标的证券-申银万国今日与上一交易日标的或比例变动
SELECT 来源='申银万国',A.信息发布日期,A.证券代码,A.变动类别,A.保证金比例,B.信息发布日期,B.证券代码,B.变动类别,B.保证金比例,A.ID
FROM
(SELECT FORMAT(XXFBRQ,'yyyy-MM-dd') 信息发布日期,XXLY 信息来源,ZQDM 证券代码,BDLB 变动类别,
CONCAT(FLOOR(BZJBL*100),'%') 保证金比例,ID
FROM  [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ
WHERE XXFBRQ=(SELECT TOP 1 RQ FROM   [10.101.0.212].JYPRIME.dbo.usrJYR WHERE ZQSC=83 AND SFJYR=1 AND RQ<=CONVERT(VARCHAR(10),GETDATE(),120) ORDER BY RQ DESC) AND JGDM=41169)A
FULL JOIN
(SELECT FORMAT(XXFBRQ,'yyyy-MM-dd') 信息发布日期,XXLY 信息来源,ZQDM 证券代码,BDLB 变动类别,
CONCAT(FLOOR(BZJBL*100),'%') 保证金比例
FROM   [10.101.0.212].JYPRIME.dbo.usrRZRQBDZQ
WHERE XXFBRQ=(SELECT TOP 1 RQ FROM   [10.101.0.212].JYPRIME.dbo.usrJYR WHERE ZQSC=83 AND SFJYR=1 AND RQ<CONVERT(VARCHAR(10),GETDATE(),120) ORDER BY RQ DESC)
AND JGDM=41169)B
ON A.证券代码=B.证券代码 AND A.变动类别=B.变动类别
WHERE (A.证券代码 IS NULL OR B.证券代码 IS NULL)
OR (A.保证金比例<>B.保证金比例)